version: '3'
services:
  wol-webhook:
    build: .
    network_mode: host
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - WOL_MAC=${WOL_MAC}
      - WOL_TOKEN=${WOL_TOKEN}
    env_file:
      - .env
